services:
  - type: web
    name: oftw-vizro-dashboard
    env: python
    buildCommand: cd app && pip install -r requirements.txt
    startCommand: cd app && gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: .
    healthCheckPath: /
    autoDeploy: true
    plan: free 